### ISSUE TITLE
Contrastive learning implementation different from the paper?

### ISSUE THREAD

**Issue by CheongWoong** [YaoMarkMu/DOMINO_MB-MetaRL#1]
The implementaion of contrastive learning looks different from stated in the paper.

The paper says that positive samples are from the same episode and negative samples are from different episodes.
However, in this implementation, samples from different episodes (shuffled following the batch axis) are used as positive ones and samples generated by other ensemble models are used as negative samples.

I followed the instructions in README to run the experiments. I am worried if I have misunderstood anything.

https://github.com/YaoMarkMu/DOMINO_MB-MetaRL/blob/6e4de91e90f68b37b1a95e3aebdc41e4b6007a49/domino/dynamics/core/utils.py#L785-L815

**Comment by siaoliu** [comment]
Don be worry, this implementation is hard to read, the positive sample are shuffled feature from the same batch and negtive is from different branch/blocks.
Besides, I am not undertand the infer_info_nce with infer_info_nce_C. Can you give me some help ???

" This implementation cannot be said to be exactly the same as the original paper, but rather completely unrelated. "

**Comment by YaoMarkMu** [comment]
Thank your good question. Sorry for the confusion. I appreciate your attention to detail and would be happy to clarify any confusion you may have.

This implementation is based on a feature of our codebase T-MCL, which employs a data sampler to provide each ensemble model with data sampled from different dynamics parameters obtained by undersampling data from distinct episodes. Moreover, when constructing a batch of data for the same model, trajectory segments generated under the same dynamics parameters are selected. Consequently, this implementation is currently a more convenient approach to constructing batches of data for contrastive learning.

**Comment by YaoMarkMu** [comment]
> Don be worry, this implementation is hard to read, the positive sample are shuffled feature from the same batch and negtive is from different branch/blocks. Besides, I am not undertand the infer_info_nce with infer_info_nce_C. Can you give me some help ???


Initially, we designed two separate functions to compute different infonce, allowing for internal adjustments and modifications to hyperparameters. However, we later realized that they could utilize the same form and hyperparameters. As a result, the current version is redundant, and we apologize for not catching this during the organization process. We will review and improve the code accordingly. Thank you for providing us with your valuable feedback.

**Comment by siaoliu** [comment]
> 
Thanks for your quick reply.
I noticed that the context encoder includes a code like that :
output=tf.concat([tf.expand_dims(output_head,0), tf.expand_dims(cons_head[0],0), tf.expand_dims(cons_head[1],0)], 0) 
as the context output, which may mean take the entangled and disentangled vectors simultaneously into account.

**Comment by CheongWoong** [comment]
Thank you so much for clarification.
